#!/bin/bash

[ "$__INCLUDES_INCLUDED__" != "" ] && return
__INCLUDES_INCLUDED__=True

MCC_FOLDER=${MCC_FOLDER:-$(dirname $0)}
source "$MCC_FOLDER/config"
source "$MCC_FOLDER/lib/common"
source_folder "$MCC_FOLDER/operations"
source_folder "$MCC_FOLDER/lib"
source "$MCC_FOLDER/platform/platform"