#!/bin/bash
#
# MCC - My Container Cluster
# https://github.com/dealfonso/my_container_cluster
#
# Copyright (C) GRyCAP - I3M - UPV 
# Developed by Carlos A. caralla@upv.es
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
[ "$__INCLUDES_INCLUDED__" != "" ] && return
__INCLUDES_INCLUDED__=True

source "$MCC_FOLDER/version"
source "$MCC_FOLDER/lib/common"
source_folder "$MCC_FOLDER/operations"
source_folder "$MCC_FOLDER/lib"
source "$MCC_FOLDER/platform/platform"