#!/bin/bash
function delnode() {
    local CLUSTERNAME=
    local NODES=
    local ALL=False

    reset_help
    add_help_cmd "<cluster name>" "name of the cluster to which the node is going to be added to"
    add_help_cmd "<node1>..<nodeN>" "name of the nodes to delete"
    add_help_cmd "--all|-a" "delete all the nodes of the cluster (except the front-end)"
    while (( $# > 0 )); do
        case "$1" in
            --all|-a)        ALL=True;;
            --help|-h)       usage delnode && exit 0;;

            *)  if [ "$CLUSTERNAME" == "" ]; then 
                    CLUSTERNAME=$(ensure_valid_clustername $1)
                else
                    NODES="${NODES}$1"
                fi;;
        esac
        shift
    done

    # If the cluster does not exist, fail
    cluster_exists "$CLUSTERNAME" || return 1

    local ALLNODES=
    output_to_var_or_fail ALLNODES "could not get the list of nodes from the cluster $CLUSTERNAME" get_nodes_of_cluster "$CLUSTERNAME" || 
        return 1

    # The simple mechanism is to consider the same list
    if [ "$ALL" == "True" ]; then
        NODES="$ALLNODES"
    fi

    local NODENAME
    local VALID_NODE

    # Before deleting the nodes, check if all of them are valid (we will not do anything in other case)
    for NODENAME in $NODES; do
        VALID_NODE=$(echo "$ALLNODES" | sed -n "s/^.*[[:blank:]]*\($NODENAME\)\([[:blank:]]\+\|$\).*/\1/p")
        if [ "$NODENAME" != "$VALID_NODE" ]; then
            p_error "node $NODENAME is not part of cluster $CLUSTERNAME"
            return 1
        fi
    done

    local FAILED=0
    local FAILED_REMOVE=0
    for NODENAME in $NODES; do
        if [ "$NODENAME" != "" ]; then
            # Will stop the container and remove it from the cluster
            p_info "stopping the container $NODENAME"

            ERR_STR=$(lxc stop "$NODENAME" 2>&1)
            if (($? != 0)); then
                p_error "could not stop node $NODENAME ($ERR_STR)"
                FAILED=$((FAILED+1))
            else
                p_debug "container $NODENAME successfully stopped"

                # Finally we MUST remove the node from the front-end    
                NODEID="$(get_nodeid_from_nodename $NODENAME)"

                p_debug "removing node $NODENAME from the cluster $CLUSTERNAME"
                if ! execute_in_container "$CLUSTERNAME" "$MLC_REMOTE_FOLDER/$MLC_SCRIPT_DELNODE" "$NODENAME" "255.255.255.255" "${NODEID}" "${NODENAME}" "${NODEID}.${CLUSTERNAME}"; then
                    p_error "failed to remove the node to the cluster"
                    ((FAILED_REMOVE++))
                fi
            fi
        fi
    done

    # Show errors if they have happened
    if ((FAILED_REMOVE>0)); then
        p_error "some nodes failed to be removed from the cluster"
    fi

    if ((FAILED>0)); then
        p_error "some nodes failed to stop"
        return 1
    fi
    
    return 0
}
