#!/bin/bash
#
# MCC - My Container Cluster
# https://github.com/dealfonso/my_container_cluster
#
# Copyright (C) GRyCAP - I3M - UPV 
# Developed by Carlos A. caralla@upv.es
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

function delnode() {
    local CLUSTERNAME=
    local NODES=
    local ALL=False

    _HELP__reset_help
    _HELP__append_description "Removes one or more nodes from a cluster. The script remove-node is invoked in the cluster, prior to deleting the container."
    _HELP__add_help_cmd "<cluster name>" "name of the cluster to which the node is going to be added to"
    _HELP__add_help_cmd "<node1>..<nodeN>" "name of the nodes to delete"
    _HELP__add_help_cmd "--all|-a" "delete all the nodes of the cluster (except the front-end)"
    _HELP__add_help_cmd "--help|-h" "shows this help and exists"    
    while (( $# > 0 )); do
        case "$1" in
            --all|-a)        ALL=True;;
            --help|-h)       _HELP__usage delnode && exit 0;;

            *)  if [ "$CLUSTERNAME" == "" ]; then 
                    CLUSTERNAME="$1"
                else
                    NODES="${NODES}$1 "
                fi;;
        esac
        shift
    done

    # Ensure that we have a valid name for the cluster
    CLUSTERNAME="$(_NAMING__ensure_valid_clustername "$CLUSTERNAME")" || return 1

    # If the cluster does not exist, fail
    if ! _CLUSTER__exists "$CLUSTERNAME"; then
        p_error "cluster $CLUSTERNAME does not exist"
        return 2
    fi

    if [ "$NODES" == "" -a "$ALL" != "True" ]; then
        p_error "no nodes to delete"
        return 3
    fi

    local ALLNODES=
    output_to_var_or_fail ALLNODES "could not get the list of nodes from the cluster $CLUSTERNAME" _CLUSTER__get_nodes "$CLUSTERNAME" || 
        return 3

    # The simple mechanism is to consider the same list
    if [ "$ALL" == "True" ]; then
        NODES="$ALLNODES"
    fi

    local NODENAME
    local VALID_NODE

    # Before deleting the nodes, check if all of them are valid (we will not do anything in other case)
    for NODENAME in $NODES; do
        if ! element_in_list "$NODENAME" "$ALLNODES"; then
            p_error "node $NODENAME is not part of cluster $CLUSTERNAME"
            return 1
        fi
    done

    local FAILED=0
    local FAILED_REMOVE=0
    local FAILED_DISCONNECT=0
    local FAILED_DISPOSE=0
    local FAILED_CURRENT
    for NODENAME in $NODES; do
        if [ "$NODENAME" != "" ]; then
            FAILED_CURRENT=False

            p_info "disconnecting devices from $NODENAME"
            if ! _MCC__devices_disconnect "$NODENAME"; then
                p_warning "failed to disconnect some devices"
                ((FAILED_DISCONNECT++))
                FAILED_CURRENT=True
            fi

            # Will stop the container and remove it from the cluster
            p_info "stopping the container $NODENAME"

            _CONTAINER__stop "$NODENAME"
            if (($? != 0)); then
                FAILED=$((FAILED+1))
                FAILED_CURRENT=True
            else
                # Finally we MUST remove the node from the front-end    
                NODEID="$(_NAMING__get_nodeid_from_nodename $NODENAME)"

                p_debug "removing node $NODENAME from the cluster $CLUSTERNAME"
                if ! _CONTAINER__execute "$CLUSTERNAME" "$MCC_REMOTE_FOLDER/$MCC_SCRIPT_REMOVENODE" "$NODENAME" "255.255.255.255" "${NODEID}" "${NODENAME}" "${NODEID}.${CLUSTERNAME}"; then
                    p_error "failed to remove the node to the cluster"
                    ((FAILED_REMOVE++))
                    FAILED_CURRENT=True
                fi
                
                p_out "node $NODENAME removed from cluster $CLUSTERNAME"
            fi

            p_info "disposing devices from $NODENAME"
            if ! _MCC__devices_dispose "$NODENAME"; then
                p_warning "failed to dispose some devices"
                ((FAILED_DISPOSE++))
                FAILED_CURRENT=True
            fi

            if [ "$FAILED_CURRENT" == "False" ]; then
                p_info "node $NODENAME deleted"
            else
                p_warning "something failed when deleting node $NODENAME"
            fi
        fi
    done

    # Show errors if they have happened
    if ((FAILED_REMOVE>0)); then
        p_error "some nodes failed to be removed from the cluster"
    fi

    if ((FAILED_DISCONNECT>0)) || ((FAILED_DISPOSE>0)); then
        p_error "failed to deal with the devices"
        return 2
    fi

    if ((FAILED>0)); then
        p_error "some nodes failed to stop"
        return 1
    fi
    
    return 0
}
