#!/bin/bash
function enter() {
    local CLUSTERNAME=
    local DELETE=

    _HELP__reset_help
    _HELP__add_help_cmd "--help|-h" "shows this help and exists"
    _HELP__add_help_cmd "--delete-on-exit|-D" "deletes the cluster once the session has finished"
    _HELP__add_help_cmd "<cluster name>" "name of the cluster in which to enter"
    while (( $# > 0 )); do
        case "$1" in
            --help|-h)              _HELP__usage enter && exit 0;;
            --delete-on-exit|-D)    DELETE=True;;

            *)  if [ "$CLUSTERNAME" == "" ]; then 
                    CLUSTERNAME=$1
                else
                    _HELP__usage addnode && exit 1
                fi;;
        esac
        shift
    done

    CLUSTERNAME="$(_NAMING__ensure_valid_clustername "$CLUSTERNAME")" || return 1

    # If the cluster does not exist, fail
    _CLUSTER__exists "$CLUSTERNAME" || return 1

    # enter in the cluster
    local ENTERED=False
    for shell in $MCC_SHELLS; do
        p_debug "trying shell $shell"
        if _CONTAINER__execute "$CLUSTERNAME" which "$shell" > /dev/null 2> /dev/null; then
            _CONTAINER__execute "$CLUSTERNAME" "$shell"
            ENTERED=True
            break;
        fi
        p_warning "could not init session using shell $shell"
    done

    if [ "$ENTERED" != "True" ]; then
        p_error "did not manage to use any of the configured shells. Please check the MCC_SHELLS variable"
        return 2
    fi

    # if the user has requested to delete the cluster, invoke the function to delete it
    if [ "$DELETE" == "True" ]; then
        if ! delete "$CLUSTERNAME"; then
            p_error "failed to delete the cluster $CLUSTERNAME"
            return 2
        fi
    fi
    return 0
}
