#!/bin/bash
#
# MCC - My Container Cluster
# https://github.com/dealfonso/my_container_cluster
#
# Copyright (C) GRyCAP - I3M - UPV 
# Developed by Carlos A. caralla@upv.es
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

function enter() {
    local CLUSTERNAME=
    local DELETE=

    _HELP__reset_help
    _HELP__append_description "Gets a shell to the cluster. It tries to use some of the following shells: $MCC_SHELLS"
    _HELP__add_help_cmd "--help|-h" "shows this help and exists"
    _HELP__add_help_cmd "--delete-on-exit|-D" "deletes the cluster once the session has finished"
    _HELP__add_help_cmd "<cluster name>" "name of the cluster in which to enter"
    while (( $# > 0 )); do
        case "$1" in
            --help|-h)              _HELP__usage enter && exit 0;;
            --delete-on-exit|-D)    DELETE=True;;

            *)  if [ "$CLUSTERNAME" == "" ]; then 
                    CLUSTERNAME=$1
                else
                    _HELP__usage addnode && exit 1
                fi;;
        esac
        shift
    done

    CLUSTERNAME="$(_NAMING__ensure_valid_clustername "$CLUSTERNAME")" || return 1

    # If the cluster does not exist, fail
    _CLUSTER__exists "$CLUSTERNAME" || return 1

    # enter in the cluster
    local ENTERED=False
    for shell in $MCC_SHELLS; do
        p_debug "trying shell $shell"
        if _CONTAINER__execute "$CLUSTERNAME" which "$shell" > /dev/null 2> /dev/null; then
            _CONTAINER__execute "$CLUSTERNAME" "$shell"
            ENTERED=True
            break;
        fi
        p_warning "could not init session using shell $shell"
    done

    if [ "$ENTERED" != "True" ]; then
        p_error "did not manage to use any of the configured shells. Please check the MCC_SHELLS variable"
        return 2
    fi

    # if the user has requested to delete the cluster, invoke the function to delete it
    if [ "$DELETE" == "True" ]; then
        if ! delete "$CLUSTERNAME"; then
            p_error "failed to delete the cluster $CLUSTERNAME"
            return 2
        fi
    fi
    return 0
}
