#!/bin/sh
set -x
mkdir -p /root/.ssh
chmod 700 /root/.ssh
rm -f /root/.ssh/id_rsa
set -e
ssh-keygen -t rsa -N "" -f /root/.ssh/id_rsa

cat > /root/.ssh/config << EOT
Host `hostname`* node*
StrictHostKeyChecking no
LogLevel quiet
UserKnownHostsFile /dev/null
EOT
exit 0
