#!/bin/bash

function _CLUSTER__exists() {
    local CLUSTERNAME=$1

    # Get the list of clusters
    local CLUSTERS
    output_to_var_or_fail CLUSTERS "could not get the list of clusters cluster does not exist" _CLUSTER__get_list || return 2

    # Now get only those names that match the substring of the name that we are searching
    local CLUSTERS_FILTERED=$(echo "$CLUSTERS" | grep "$CLUSTERNAME" | tr -d ' ')
    while read C_NAME; do
        if [ "$C_NAME" == "$CLUSTERNAME" ]; then
            return 0;
        fi
    done <<< "$CLUSTERS"

    # If not matched, the cluster does not exist
    p_error "the cluster '$CLUSTERNAME' does not exist"
    return 1
}

function _CLUSTER__get_list() {
    local CONTAINER_STR
    output_to_var_or_fail CONTAINER_STR "could not get the list of containers" _MLC__get_container_list ||
        return 1

    # Only those containers that have the form mlc-<name> are the frontends. If they have a "-node" at the end, they are not clusters themselves
    local CNAME CNAME_C
    while read CNAME; do
        CNAME_C="${CNAME%-node*}"
        if [ "$CNAME_C" == "$CNAME" ]; then
            echo "$CNAME"
        fi
    done <<< "$CONTAINER_STR"
    return 0
}

function _CLUSTER__get_nodes() {
    local CLUSTERNAME="$1"

    # Get the list of containers
    local CONTAINER_STR
    output_to_var_or_fail CONTAINER_STR "could not get the list of containers" _MLC__get_container_list ||
        return 1

    # Only those that have the form CLUSTERNAME-nodeXXX are nodes from the cluster
    local CNAME CNAME_C
    while read CNAME; do
        if [[ "$CNAME" =~ ^$CLUSTERNAME-node[0-9]*$ ]]; then
            echo "$CNAME"
        fi
    done <<< "$CONTAINER_STR"
    return 0
}

function _CLUSTER__get_info() {
    local CLUSTERNAME="$1"

    local NODES=
    output_to_var_or_fail NODES "could not get the list of nodes from the cluster $CLUSTERNAME" _CLUSTER__get_nodes "$CLUSTERNAME" || 
        return 1

    local NETWORKS
    output_to_var_or_fail NETWORKS "could not obtain the networks associated to $CLUSTERNAME" _CONTAINER__get_networks "$CLUSTERNAME" || 
        return 2

    local IPS
    output_to_var_or_fail IPS "could obtain the ip addresses associated to $CLUSTERNAME" _NETWORK__get_node_ip "$CLUSTERNAME" || 
        return 3
    
    echo "$CLUSTERNAME;$NETWORKS;$IPS;$NODES"
    return 0
}