#!/bin/bash
#
# MCC - My Container Cluster
# https://github.com/dealfonso/my_container_cluster
#
# Copyright (C) GRyCAP - I3M - UPV 
# Developed by Carlos A. caralla@upv.es
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

declare UNDO_CMDS=

function _UNDO__clear() {
    #
    # $ Usage: _UNDO__clear
    #
    # Clears the list of commands to undo an operation
    UNDO_CMDS=
}

function _UNDO__add_undo_cmdline() {
    #
    # $ Usage: _UNDO__add_undo_cmdline <command line> 
    #
    # Appends a new command to undo a situation
    UNDO_CMDS="${UNDO_CMDS}$@
"
}

function _UNDO__execute() {
    #
    # $ Usage: _UNDO__execute
    #
    # Executes the list of commands that revert a situation, in the same order that they were issued
    if [ "$UNDO_CMDS" != "" ]; then
        p_debug "trying to undo the commands"
    
        local LINE
        while read LINE; do
            execute_command "$LINE"
        done <<< "$(echo "${UNDO_CMDS}" | tac - | tail -n +2)"
    fi
}