#!/bin/sh
CONTAINERNAME="$1"
IPADDR="$2"
shift
shift
NODENAMES="$@"

# First of all, we remove all the entries in /etc/hosts that contain the IP address
sed -i "/^[[:blank:]]*${IPADDR}[[:blank:]]\+/d" /etc/hosts

# Now we remove the entries that has any of the node names
for NODENAME in $NODENAMES; do
    sed -i "/[[:blank:]]\+${NODENAME}\([[:blank:]]\+\|$\)/d" /etc/hosts
done

echo "" >> /etc/hosts
echo "${IPADDR} ${NODENAMES}" >> /etc/hosts

BASEDIR=/etc/mcc/addnode.d
error=0
if [ -d $BASEDIR ]; then
    for scriptname in $BASEDIR/*; do
        if [ ! -d "$scriptname" -a -x "$scriptname" ]; then
            $scriptname > /var/log/mcc-addnode.log 2>/var/log/mcc-addnode.log
            if [ $? -ne 0 ]; then
                error=$[ $error + 1 ]
            fi
        fi
    done
fi

exit $error