#!/bin/sh

BASEDIR=/etc/mcc/
{
if [ -d $BASEDIR ]; then
    for scriptname in $BASEDIR/*; do
        if [ ! -d "$scriptname" -a -x "$scriptname" ]; then
            $scriptname > /var/log/mcc.log 2>/var/log/mcc.log
            if [ $? -eq 0 ]; then
                echo -e "Execution of $scriptname [\e[32msucceeded\e[0m]"
            else
                echo -e "Execution of $scriptname [\e[31mfailed\e[0m]"
            fi
        fi
    done
fi
} 