#!/bin/sh
#
# MCC - My Container Cluster
# https://github.com/dealfonso/my_container_cluster
#
# Copyright (C) GRyCAP - I3M - UPV 
# Developed by Carlos A. caralla@upv.es
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

CONTAINERNAME="$1"
IPADDR="$2"
shift
shift
NODENAMES="$@"

# First of all, we remove all the entries in /etc/hosts that contain the IP address
sed -i "/^[[:blank:]]*${IPADDR}[[:blank:]]\+/d" /etc/hosts

# Now we remove the entries that has any of the node names
for NODENAME in $NODENAMES; do
    sed -i "/[[:blank:]]\+${NODENAME}\([[:blank:]]\+\|$\)/d" /etc/hosts
done

echo "127.0.0.1 ${NODENAMES}" >> /etc/hosts
exit 0